# Generated by Django 6.0.2 on 2026-02-13 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cheatingevent_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='audio_recording',
            field=models.FileField(blank=True, null=True, upload_to='interviews/audio/'),
        ),
        migrations.AddField(
            model_name='interview',
            name='average_voice_confidence',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='interview',
            name='video_recording',
            field=models.FileField(blank=True, null=True, upload_to='interviews/video/'),
        ),
    ]
